version: 2

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
  system_packages: true

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: true

formats:
  - htmlzip
